"""Phase 1: Add stale content detection and cleanup fields

Revision ID: ad30f6583811
Revises: f5e26cb194bb
Create Date: 2025-11-02 10:20:22.069512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad30f6583811'
down_revision: Union[str, Sequence[str], None] = 'f5e26cb194bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_copies', sa.Column('stored_content_hash', sa.String(length=64), nullable=True))
    op.add_column('document_copies', sa.Column('stored_size', sa.Integer(), nullable=True))
    op.add_column('document_copies', sa.Column('stored_mtime', sa.Float(), nullable=True))
    op.add_column('document_copies', sa.Column('lastSeenAt', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_document_copies_lastSeenAt'), 'document_copies', ['lastSeenAt'], unique=False)
    # Skip constraint modifications for SQLite compatibility
    # The content_hash unique constraint/index already exists from previous migration
    op.add_column('pending_operations', sa.Column('document_content_hash', sa.String(length=64), nullable=True))
    op.add_column('pending_operations', sa.Column('model_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_operations', 'model_name')
    op.drop_column('pending_operations', 'document_content_hash')
    # Skip constraint modifications for SQLite compatibility
    op.drop_index(op.f('ix_document_copies_lastSeenAt'), table_name='document_copies')
    op.drop_column('document_copies', 'lastSeenAt')
    op.drop_column('document_copies', 'stored_mtime')
    op.drop_column('document_copies', 'stored_size')
    op.drop_column('document_copies', 'stored_content_hash')
    # ### end Alembic commands ###
